### ISSUE TITLE
acceptMetamaskAccess() failing with cy.task() error

### ISSUE THREAD

**Issue by mflorlorenzo** [Synthetixio/synpress#800]
**Describe the bug**
acceptMetamaskAccess() is failing.

`
CypressError: `cy.task()` must only be invoked from the spec file or support file.

From Your Spec Code:
      at Context.eval (webpack:///./node_modules/@synthetixio/synpress/support/commands.js:184:0)
`

**To Reproduce**
1. Run the project
2. Wait until framework has to accept the metamask login access
3. See error

**Related repository**
Link to repository related with this issue.

**Expected behavior**
Login successfully. acceptMetamaskAccess() should works as it did before.

**Desktop (please complete the following information):**
 - OS: macOS 12.6.5
 - Synpress version: 3.7.1
- running locally

**Additional context**
There was an issue on cypress related to the new version (12.15.0), but I'm using an old one (12.11.0), so should works.
https://github.com/cypress-io/code-coverage/issues/667

**Comment by ayushrungta8** [comment]
@mflorlorenzo I also faced the same issue a few days ago. For me the thing was even though I had gone back to an older version the test run was still using the latest version. You can try by checking the starting of the test where it shows all the spec files and other info

**Comment by mflorlorenzo** [comment]
I tried updating cypress to 12.16.0 where that issues is fixed, but still got the same issue.
Also I see to many warnings on synpress having unmet peer dependencies in some packages.

**Comment by mflorlorenzo** [comment]
Well, I found the issue. 
I changed the cypress version from 12.16.0 to 12.14.0 on @synthetixio/synpress/node_modules/cypress/package.json and works !
@synthetixio-team is there a chance to take a look on it please? From Cypress say version 12.16.0 has the fix for this error, but it's not working here. Thanks

**Comment by aziolek** [comment]
@mflorlorenzo: it's not Synpress's fault. As Cypress team expressed [here](https://github.com/cypress-io/code-coverage/issues/667#issuecomment-1609563639) they know about some edge cases that still exist in `12.16.0`. I do confirm that pinning Cypress version to `12.14.0` solves the problem for me too.
